stages:
  - build
  - deploy

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER
      -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - echo "Building the Docker image"
    - sleep 5
    - echo "Build completed successfully"
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure

deploy:
  stage: deploy
  image: uhligit/ansible
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" > .key
    - chmod 400 .key
    - ssh-add .key
  script:
    - ANSIBLE_CONFIG=ansible.cfg ansible-playbook -i hosts wordpress.yml