- name: Compose Wordpress
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: compose.yaml.j2, dest: /opt/wordpress/compose.yaml }
    - { src: .env.j2, dest: /opt/wordpress/.env }
    - { src: Caddyfile.j2, dest: /opt/wordpress/Caddyfile}
  notify: Restart Wordpress

- name: up
  shell: |
    docker compose -f compose.yaml up -d
  args:
    chdir: /opt/wordpress
