---
- name: Download Zabbix release package
  get_url:
    url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-6+ubuntu24.04_all.deb
    dest: /tmp/zabbix-release_6.0-6+ubuntu24.04_all.deb

- name: Install Zabbix release package
  apt:
    deb: /tmp/zabbix-release_6.0-6+ubuntu24.04_all.deb
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Zabbix agent
  apt:
    name: zabbix-agent
    state: present


- name: Restart Zabbix agent service
  systemd:
    name: zabbix-agent
    state: restarted

- name: Enable Zabbix agent service
  systemd:
    name: zabbix-agent
    enabled: yes